server:
  servlet:
    # 指定服务器的内容根路径
    context-path: /mall-app/api
spring:
  jpa:
    # 用于Jpa控制台调试
    database-platform: org.hibernate.dialect.MySQLDialect
    # 表不存在时自动创建，之后更新
    hibernate:
      ddl-auto: update
    # 显示和格式化sql控制台输出
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    username: admin
    password: 123
    url: jdbc:mysql://localhost:3306/MallApp
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 不使用ssl，指定时区，允许使用公钥
    hikari:
      data-source-properties:
        useSSL: false
        serverTimezone: GMT-8
        allowPublicKeyRetrieval: true
    tomcat:
      db-properties:
        close-method: close
  jackson:
    # 防止序列化空对象时出错
    serialization:
      fail-on-empty-beans: false
